"""Core ALAMATIN package."""

from .evaluation_metrics import (
    CRITICAL_ENTITY_TYPES,
    EntityMetricResult,
    LatencySummary,
    RateResult,
    RecallResult,
    binary_recall,
    canonical_json_sha256,
    critical_exact_match,
    entity_metrics,
    entity_metrics_by_type,
    extract_bio_entities,
    false_correction_rate,
    latency_summary_ms,
    nearest_rank_percentile,
)
from .label_schema import (
    BIO_LABELS,
    ENTITY_TYPES,
    ID_TO_LABEL,
    LABEL_TO_ID,
    SCHEMA_VERSION,
    validate_bio_sequence,
)
from .reference_hierarchy import (
    REFERENCE_SCHEMA_VERSION,
    LookupResult,
    ReferenceHierarchy,
    ReferenceRow,
    ReferenceValidationError,
    SourceReference,
    normalize_name,
    normalize_region_code,
)
from .osm_pbf import OsmNode, OsmPbfError, OsmWay, iter_nodes_and_ways, iter_primitive_blocks
from .regex_baseline import tag_text, tag_tokens
from .tokenizer import tokenize

__all__ = [
    "BIO_LABELS",
    "CRITICAL_ENTITY_TYPES",
    "ENTITY_TYPES",
    "EntityMetricResult",
    "ID_TO_LABEL",
    "LABEL_TO_ID",
    "LatencySummary",
    "RateResult",
    "RecallResult",
    "REFERENCE_SCHEMA_VERSION",
    "ReferenceHierarchy",
    "ReferenceRow",
    "ReferenceValidationError",
    "SCHEMA_VERSION",
    "SourceReference",
    "binary_recall",
    "canonical_json_sha256",
    "critical_exact_match",
    "entity_metrics",
    "entity_metrics_by_type",
    "extract_bio_entities",
    "false_correction_rate",
    "latency_summary_ms",
    "LookupResult",
    "nearest_rank_percentile",
    "normalize_name",
    "normalize_region_code",
    "OsmNode",
    "OsmPbfError",
    "OsmWay",
    "iter_nodes_and_ways",
    "iter_primitive_blocks",
    "tag_text",
    "tag_tokens",
    "tokenize",
    "validate_bio_sequence",
]
